### ISSUE TITLE
How did you create the bit manipulation SVGs?

### ISSUE THREAD

**Issue by adworacz** [Validark/validark.github.io#2]
I came across your site while looking at your work with Zig (which really is a fabulous language), and I was particularly impressed with the SVGs that you've put together that explain the bit operations on your post: https://validark.github.io/find_nth_set_bit.html

I'm really curious as to how you created these SVGs, as they do a wonderful job of visually explaining what's going on.

**Comment by Validark** [comment]
Hello @adworacz. Those SVG's were hand-coded.

https://github.com/Validark/validark.github.io/blob/1aab8cbec87911b3eb795c414ad7171b2fdf9ee2/find_nth_set_bit.html#L127-L203

I did do some code-editor tricks to write a bunch of the lines of code all at once, but the layout was derived from just entering numbers that change by an amount that I thought looked right.

Almost my entire website is hand-coded, actually! Only 3 of the SVG diagrams in my [DynSDT paper](https://validark.github.io/DynSDT) were generated with a tool, because they were originally created in an HTML5 Canvas.

**Comment by adworacz** [comment]
Consider me impressed then. I hadn't really considered hand coding SVGs, but I think you provide a pretty strong argument here.

Thank you for your answers!

**Comment by Validark** [comment]
Thank you for appreciating some of my work! It definitely helps motivate me to work on cool stuff when I know there are people interested in seeing the things I do.

I have a talk coming up if you are interested in watching the livestream (or coming in person, if you're in the vicinity!) It will be about my Zig tokenizer and parser, and all the techniques employed to gain performance! 

https://www.meetup.com/utah-zig/events/300379227/

**Comment by adworacz** [comment]
Very cool! 

I'm not in the area, but I hope to watch the talk at some point. Do you know if it will be recorded? I might have a work conflict with that time is all. :)

**Comment by Validark** [comment]
Yes, it will be recorded and posted to this channel: https://www.youtube.com/@utahzig/streams

**Comment by adworacz** [comment]
Awesome, thank you!
